application: simplesage389
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: simplesage.app

libraries:
- name: jinja2
  version: "2.6"

inbound_services:
- channel_presence
